FORMAT: 1A
# WTTJ-test API documentation

# Group Lists

## Get Lists [/lists]

### GET Lists [GET]

+ Request returns all lists (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Headers

            

    + Body

            [
              {
                "id": 72,
                "title": "test_title",
                "created_at": "2018-12-01T13:17:25.089Z",
                "updated_at": "2018-12-01T13:17:25.089Z"
              },
              {
                "id": 73,
                "title": "test_title",
                "created_at": "2018-12-01T13:17:25.094Z",
                "updated_at": "2018-12-01T13:17:25.094Z"
              }
            ]
